version: '3'

services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "3002:3002"
    depends_on:
      - mongo
    environment:
      MONGO_URI: "mongodb://username:password@mongo:27017/comp3123db"

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend